"""Shared PostgreSQL persistence primitives for MeuFinanceiro."""

from meufinanceiro_persistence.banking import (
    BankingConnectionRecord,
    BankingIntegrationStore,
    BankingPersistenceError,
    CapabilitySnapshot,
    ConfigurationConflictError,
    ConfigurationNotFoundError,
    ConnectionCapabilityRecord,
    ConnectionConflictError,
    ConnectionNotFoundError,
    ProviderConfigurationRecord,
    ProviderConfigurationState,
    ProviderNotEnabledError,
    StoredCapability,
    StoredCapabilitySource,
    StoredCapabilityState,
    StoredConnectionStatus,
    credential_aad,
)
from meufinanceiro_persistence.database import Database
from meufinanceiro_persistence.demo import (
    DEMO_CONTRACT_CHECKSUM,
    DEMO_CURRENCY,
    DEMO_FIXTURE_ID,
    DEMO_FIXTURE_VERSION,
    DEMO_REFERENCE_DATE,
    DEMO_SCOPE,
    DEMO_TIMEZONE,
    DemoFixtureConflictError,
    DemoFixtureStatus,
    DemoFixtureStore,
    DemoModeDisabledError,
    unloaded_demo_status,
)
from meufinanceiro_persistence.health import (
    PersistenceHealth,
    inspect_persistence_health,
)
from meufinanceiro_persistence.queue import (
    LostLeaseError,
    TaskQueue,
    TaskRecord,
    TaskStatus,
)

__all__ = [
    "DEMO_CONTRACT_CHECKSUM",
    "DEMO_CURRENCY",
    "DEMO_FIXTURE_ID",
    "DEMO_FIXTURE_VERSION",
    "DEMO_REFERENCE_DATE",
    "DEMO_SCOPE",
    "DEMO_TIMEZONE",
    "BankingConnectionRecord",
    "BankingIntegrationStore",
    "BankingPersistenceError",
    "CapabilitySnapshot",
    "ConfigurationConflictError",
    "ConfigurationNotFoundError",
    "ConnectionCapabilityRecord",
    "ConnectionConflictError",
    "ConnectionNotFoundError",
    "Database",
    "DemoFixtureConflictError",
    "DemoFixtureStatus",
    "DemoFixtureStore",
    "DemoModeDisabledError",
    "LostLeaseError",
    "PersistenceHealth",
    "ProviderConfigurationRecord",
    "ProviderConfigurationState",
    "ProviderNotEnabledError",
    "StoredCapability",
    "StoredCapabilitySource",
    "StoredCapabilityState",
    "StoredConnectionStatus",
    "TaskQueue",
    "TaskRecord",
    "TaskStatus",
    "credential_aad",
    "inspect_persistence_health",
    "unloaded_demo_status",
]
